const cityActionTypes = {
    FETCH_CITYLIST_START: 'FETCH_CITYLIST_START',
    FETCH_CITYLIST_SUCCESS: 'FETCH_CITYLIST_SUCCESS',
    FETCH_CITYLIST_FAILURE: 'FETCH_CITYLIST_FAILURE'
}

export default cityActionTypes;
