const houseActionTypes = {
    FETCH_HOUSELIST_START: 'FETCH_HOUSELIST_START',
    FETCH_HOUSELIST_SUCCESS: 'FETCH_HOUSELIST_SUCCESS',
    FETCH_HOUSELIST_FAILURE: 'FETCH_HOUSELIST_FAILURE'
};

export default houseActionTypes;